### PR TITLE
CHE-930: fix maven build of terminal with different architectures

### PR DESCRIPTION
**Pull request by garagatyi**
@skabashnyuk @evoevodin @mkuznyetsov 
Please review.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok for me.
@mkuznyetsov ?

**Comment by mkuznyetsov** [comment]
LGTM

**Comment by evoevodin** [comment]
+1

**Comment by garagatyi** [comment]
@riuvshin Please take a look

**Pull request merged**
